### ISSUE TITLE
 Integrate Style-Guide Documentation into Shared Component Repository and Storybook

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-shared-components#115]
**Description:**
The current project structure has the Style-Guide documentation located within the `portal-assets` repository under the path `https://github.com/eclipse-tractusx/portal-assets/tree/main/docs/user/Style-Guide`. To enhance the developer experience and centralize our documentation, this documentation need to get moved into the `shared-component` repo. Ensure to integrate the component descriptions into Storybook to allow users to access both the component visualizations and their usage instructions in one place.

**Acceptance Criteria:**
- All documentation under `portal-assets/docs/user/Style-Guide` is reviewed and updated if necessary.
- The documentation is moved into the `shared-component-repo` within an appropriate directory structure.
- Each component description is made available in Storybook alongside the respective component.
- "How to use" details are provided in Storybook for each component, allowing users to understand the implementation and integration process.
- Verify that all documentation is accessible and correctly formatted within Storybook.
- Documentation should be searchable within Storybook to allow for easy navigation.

**Comment by evegufy** [comment]
> Hi @manojava-gk @oyo after the merge of #264 the build of storybook fails and therefore also the publishing to npm: ![image](https://private-user-images.githubusercontent.com/46191613/357420012-a65e3fcd-1081-43d7-82af-7120adc6afea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTUwMDMsIm5iZiI6MTcyMzU1NDcwMywicGF0aCI6Ii80NjE5MTYxMy8zNTc0MjAwMTItYTY1ZTNmY2QtMTA4MS00M2Q3LTgyYWYtNzEyMGFkYzZhZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEzMTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZGU4OWQ3MzE0MDg2M2ExNTA0NDgxOGY0MzkyY2RmZjA3MWZlYzg4M2ExODUwYzVhOWM4OGJkOGE3MzNhOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KkCd1YJ_Ua8Wup2d21RmiQL84uFOzEGSdqkinBPK7Iw)
> 
> https://github.com/eclipse-tractusx/portal-shared-components/actions/runs/10351032318/job/28648672662

Please also fix the changelog before releasing the 3.1.0 version https://github.com/eclipse-tractusx/portal-shared-components/pull/264/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
