### ISSUE TITLE
Add Support to extend the Theme for shared components from Portal Frontend or any Business apps

### ISSUE THREAD

**Issue by saadanzari** [eclipse-tractusx/portal-shared-components#189]
### Description

As shared components is a benchmark of components that are used as a base in other apps as well.

**I want** to be able to modify the theme styles in Portal frontend and business apps,
**so that** we don't have to styles in the shared components and release a separate repo/ npm 

### Acceptance Criteria

- [x] [Update the SharedThemeProvider so It can pass an optional override theme]

**Comment by jjeroch** [comment]
@saadanzari  if you contribute to an ticket, please ensure the ticket is assigned to you and part of the current open source sprint.
