### ISSUE TITLE
Enhance Design Component Implementation & Documentation of `Modal`component

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-shared-components#232]
#### Description:
We have identified the need to enhance our modal components, particularly the "Modal with Sequence" types. The task involves first validating the current modal implementations to ensure they are up to date and documented properly in Storybook. Post-validation, implement the new "Modal with Sequence" element under the "Modal" category in our component library, ensuring that it meets the design specifications and is fully responsive.

#### Pre-implementation Checklist:
- [ ] Check the current number of different modal types in the codebase.
- [ ] Validate the implementation of the following modal types:
  1. Modal View Data
  2. Modal with Sequence (reduced)
  3. Modal with Sequence (extended)
- [ ] Verify the documentation and examples of each modal type in Storybook.

#### Implementation Details:
- [ ] Implement the "Modal with Sequence" component under the "Modal" category.

#### Documentation:
- [ ] Update Storybook with the new modal implementation.
- [ ] Provide usage examples for each supported component within the modal.
- [ ] Document the props and functionalities of the modal components.

---

**Modal with Sequence Example**

<img width="902" alt="image" src="https://github.com/user-attachments/assets/61cee21f-983e-4af8-ae45-093b37247626">

`NOTE: it is not yet planned to already actively use the element inside the portal; this ticket is focusing on the documentation od the modals as well as the implementation of the sequence element`

---

**Documentation for DOCS file**

#### Modal Description:

A modal is a dialog window that is displayed on top of the main application content. It is used to capture user attention and prompt them to perform an action or provide additional information without leaving the current context. Our modals are designed to be flexible and can include a variety of content, such as text, tables, input fields, buttons, and expandable components. Modals can also feature a sequence of steps which guide the user through a process.

#### Do's:

- **Use modals for critical user interactions** that require immediate attention, such as confirming a delete action or completing a multi-step process.
- **Keep the content simple and focused**. A modal should contain only what is necessary to complete the task at hand.
- **Include a clear and visible way to close the modal**, such as a close button or an 'X' in the top corner.
- **Trap focus within the modal** when it is open to maintain accessibility standards.
- **Implement keyboard navigation** within the modal, allowing users to tab through inputs and select options.
- **Use modals sparingly** to avoid disrupting the user's workflow.
- **Test modals for responsiveness** to ensure they are usable on all devices and screen sizes.
- **Document all variations** of modals in Storybook, providing clear examples of use cases.

#### Don'ts:

- **Don't overuse modals**, as they can become disruptive and annoying if they are too frequent.
- **Don't include too much information** that can overwhelm the user. Modals are meant to be focused and to-the-point.
- **Don't make modals too complex**. If a process is too long, consider breaking it up into smaller steps or using a different UI pattern.
- **Don't forget to test for accessibility**. All users should be able to interact with the modal content.
- **Don't use modals for non-essential information** that can be displayed within the main content of the page.
- **Don't neglect mobile users**. Ensure modals are just as functional and aesthetically pleasing on mobile devices.

#### Examples in Storybook:

- **Modal View Data**: This modal is used to display detailed information about a selected item from the main content. It should be read-only and provide a clear, concise view of the item's attributes.
- **Modal with Sequence (Reduced)**: Ideal for short processes or confirmations that require a minimal number of steps. It should include a progress indicator and simple navigation controls to move through the sequence.
- **Modal with Sequence (Extended)**: Best suited for longer processes that involve multiple steps. This modal should provide a clear roadmap of the process, including a progress indicator and descriptive labels for each step.

Ensure that all modals are well-documented with clear instructions on when and how to use them. Include interactive examples that demonstrate the behavior of the modal with different

**Comment by jjeroch** [comment]
Support and introduction into the whole storybook/component library by Mano and Lavanya possible

**Comment by manojava-gk** [comment]
<img width="1499" alt="Screenshot 2024-08-22 at 10 40 44 AM" src="https://github.com/user-attachments/assets/d9f39b0c-b889-46b7-8fd4-87f276328a01">

**Comment by MaximilianHauer** [comment]
new stepper looks good :)
