### ISSUE TITLE
Update to Shared Component Implementation of Card Elements

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-shared-components#233]
#### Ticket Summary:
This ticket outlines the necessary updates and enhancements required for the shared component implementation of Card Elements as per the specifications provided in the provided URLs.

#### Changes Requested:

1. **Update Add Service Card:**
   - Implement two display options for the 'Add Service Card':
     - Full Screen Version
     - Card Element Version
   - Ensure content within both versions is fully visible and properly scaled (bad example see screenhsot below)

2. **Enhance Marketplace Card:**
   - Modify the 'Marketplace Card' to support an extended image size similar to the 'App Cards' variant.

3. **Adjust App Cards Parameters:**
   - Review and clarify the parameters used in the 'App Cards' such as columns, button text, etc.
   - Ensure that the parameters are understandable and can be utilized effectively (currently not given)

#### Acceptance Criteria:

- The 'Add Service Card' should be able to switch between a full-screen view and a standard card element without content visibility issues.
- The 'Marketplace Card' must be enhanced to accommodate larger images without distorting the layout.
- The 'App Cards' must have its parameters clearly defined and documented for easy usage.

#### Technical Details:

- Source URLs for reference:
  - Add Service Card: [Add Service Card](https://eclipse-tractusx.github.io/portal-shared-components/?path=/story/cards--add-service-card)
  - Marketplace Card: [Marketplace Card](https://eclipse-tractusx.github.io/portal-shared-components/?path=/story/cards--marketplace-card)
  - App Cards: [App Cards](https://eclipse-tractusx.github.io/portal-shared-components/?path=/story/cards--app-cards&args=variant:normal)

**Comment by shahmargi12** [comment]
@jjeroch,

Can you assist me with the following?

1. Updating the Add Service Card:
- Provide the designs for both versions of the cards.

**Comment by MaximilianHauer** [comment]
@oyo could you support here ?

**Comment by oyo** [comment]
@shahmargi12 currently we have no designers any more and we have to implement the appearance by ourselves. Styling components in a way they integrate well into the existing UI. In cases where you are uncertain use a minimalistic design only rendering the required information and interaction elements and we can polish the design over time later.
