### ISSUE TITLE
Upgrade shared components dependencies (linter fails for some reason)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-shared-components#92]
[https://github.com/eclipse-tractusx/portal-shared-components]

Linter is running on fail

<img width="842" alt="image" src="https://github.com/eclipse-tractusx/portal-shared-components/assets/94133633/90fab0b8-78c8-4c89-b6ab-3225c4a56adb">

 
https://github.com/eclipse-tractusx/portal-shared-components/actions/runs/6845915412/job/18611833206?pr=67

**Comment by oyo** [comment]
closing because this was resolved with PR #116
